ktor:
    application:
        modules:
            - com.example.model.ApplicationKt.module
    deployment:
        port: 8080
#postgres:
#  url: "jdbc:postgresql://localhost/default"
#  user: username
#  password: password
mySQL:
    url: "jdbc:mysql://localhost:3306/account"
    user: "root"
    password: ""

